---
- name: Install general development packages
  become: true
  dnf:
    name:
      - zsh
      - tmux
      - vim
      - git
      - unzip
      - curl
      - wget
      - cmake
      - make
      - automake
      - gcc
      - gcc-c++
      - kernel-devel
      - python3
      - python3-pip
      - python3-devel
      - python3-setuptools
      - nodejs
    state: "latest"

#- name: Install BPF packages
  #become: true
  #dnf:
    #name:
      #- strace
      #- libbpfcc
      #- libbpfcc-dev
      #- python3-bpfcc
      #- bpfcc-tools
      #- bpftrace
    #state: "latest"
