---
- name: Install general development packages
  become: true
  dnf:
    name:
      - zsh
      - tmux
      - vim
      - git
      - unzip
      - curl
      - wget
      - cmake
      - make
      - automake
      - gcc
      - gcc-c++
      - python3
      - python3-pip
      - python3-devel
      - python3-setuptools
      - java-latest-openjdk
      - nodejs
    state: "latest"

- name: Install BPF development tools
  become: true
  dnf:
    name:
      - clang
      - llvm-strip
      - libbpf
      - libbpf-devel
      - kernel-headers
      - kernel-devel
    state: "latest"
