---
- name: Install general development packages
  become: true
  apt:
    name:
      - zsh
      - tmux
      - vim
      - git
      - unzip
      - curl
      - wget
      - cmake
      - build-essential
      - python3
      - python3-pip
      - python3-dev
      - python3-setuptools
      - nodejs
    state: "latest"

- name: Install BPF packages
  become: true
  apt:
    name:
      - strace
      - libbpfcc
      - libbpfcc-dev
      - python3-bpfcc
      - bpfcc-tools
      - bpftrace
    state: "latest"
