---

- hosts: localhost
  vars:
    user_home: /home/parallels
  tasks:
    - name: "~/.m2"
      ansible.builtin.file:
        path: "{{ user_home }}/.m2"
        state: directory

    - name: "~/.zshrc.d"
      ansible.builtin.file:
        path: "{{ user_home }}/.zshrc.d"
        state: directory

    - name: Make sure user_env.sh file is present
      ansible.builtin.file:
        path: "{{ user_home }}/.zshrc.d/user_env.sh"
        state: touch

    - name: Create Maven settings file
      template:
        src: templates/m2/settings.xml
        dest: "{{ user_home }}/.m2/settings.xml"
        mode: "600"
        force: yes

    - name: Create Netrc settings file
      template:
        src: templates/.netrc
        dest: "{{ user_home }}/.netrc"
        mode: "600"
        force: yes
